export const MEETINGS = {
  GET: "GET_MEETINGS",
  GET_SUCCESS: "GET_MEETINGS_SUCCESS",
  GET_FAIL: "GET_MEETINGS_FAIL",
  UPDATE: "UPDATE_MEETINGS",
  UPDATE_SUCCESS: "UPDATE_MEETINGS_SUCCESS",
  UPDATE_FAIL: "UPDATE_MEETINGS_FAIL",
};


export const NOTIF = {
  SHOW: "SHOW_NOTIFICATION",
  HIDE: "HIDE_NOTIFICATION"
};
